### ISSUE TITLE
Marigold -> Dye has no recipe advancement

### ISSUE THREAD

**Issue by anoomolu** [BeastSlayer666/Marigolds-Fabric-1.20.1#1]
Hiya, really cute little mod <3

I noticed that picking up a marigold doesn't give the relevant recipe advancement for crafting dye, like other flowers do. I'm on 1.20.1 fwiw.

The below should allow for that to happen when in json format in /data/advancements/recipes:

```
{
  "parent": "minecraft:recipes/root",
  "criteria": {
    "has_the_recipe": {
      "conditions": {
        "recipe": "marigolds:marigold_to_dye"
      },
      "trigger": "minecraft:recipe_unlocked"
    },
    "has_marigold": {
      "conditions": {
        "items": [
          {
            "items": [
              "marigolds:marigold"
            ]
          }
        ]
      },
      "trigger": "minecraft:inventory_changed"
    }
  },
  "requirements": [
    [
      "has_marigold",
      "has_the_recipe"
    ]
  ],
  "rewards": {
    "recipes": [
      "marigolds:marigold_to_dye"
    ]
  },
  "sends_telemetry_event": false
}
```

**Comment by BeastSlayer666** [comment]
Hey!

Thank you for taking the time to report this issue. I never would have noticed this issue on my own or known how to fix it:)

I appreciate your help teaching me something new that I can implement in Marigolds. Your report made it easy to fix. If you come across any more issues or suggestions, I would love to hear them. Your input means a lot.

Thank you for the support and for making Marigolds more vanilla-like! I hope you enjoy the newly updated marigolds! 🌻✨

Best regards,
Beast135
