### ISSUE TITLE
Tiny change re. crafting recipe

### ISSUE THREAD

**Issue by anoomolu** [BeastSlayer666/Marigolds-Fabric-1.20.1#2]
Hi! I use the recipe book instead of JEI in my small modpack, and noticed that the dye recipe isn't grouped with the vanilla orange dye recipes (from torchflower, orange tulip and red/yellow mixing). If you wanted to change that, you can add the following below the "minecraft:crafting_shapeless":

```
  "category": "misc",
  "group": "orange_dye",
```

**Comment by BeastSlayer666** [comment]
Hey!

That is another great catch. Although, I will wait a week or two before I update again. So, if another feature or issue is discovered, I could release them together.

Thank you, anoomolu! I greatly appreciate your support!:)✨🌺

**Comment by anoomolu** [comment]
The only other idea I've got at the moment is flower rings - circles of cornflowers and marigolds that show up rarely in the biomes you've listed in the mod description. Of course, it's not in line with vanilla so I'd understand if you'd rather not implement something like that. I appreciate your attention to detail with this mod :)

**Comment by BeastSlayer666** [comment]
That is an amazing idea! I love it. I do want to keep the mod as vanilla as possible but I think this idea is too amazing to leave out. I will work on that when I find time:) Thank you for this awesome idea! 🌷✨

**Comment by BeastSlayer666** [comment]
Hello!

Exciting news! Marigolds just got an update on both Curseforge and Modrinth! I'm also working on the flower rings. You can find both the data pack and mod version on Curseforge and, in the process of being listed on Modrinth.

Big thanks, anoomolu! Your support means a lot! ✨🌻
